version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    links:
      - oauth2_proxy
      - hub
      - jupyterhub
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  oauth2_proxy:
    image: oauth2_proxy
    build:
      context: .
      dockerfile: Dockerfile.oauth2_proxy
    volumes:
      - ./oauth2_proxy.cfg:/conf/oauth2_proxy.cfg
    environment:
      - OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET
      - OAUTH2_PROXY_COOKIE_DOMAIN
    healthcheck:
      disable: true

  hub:
    image: nginx:stable-alpine
    volumes:
      - ./html:/usr/share/nginx/html:ro

  jupyterhub:
    image: jupyterhub
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - /data:/data
    environment:
      - COMPOSE_PROJECT_NAME
      - CONFIGPROXY_AUTH_TOKEN=5879f3780c920dc76456360e23ef2421929b010af2440970f0f3e3ee6cca

  # nginx-proxy:
  #   image: jwilder/nginx-proxy:0.4.0
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs

  # nbviewer:
  #   image: nbviewer
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nbviewer
  #   environment:
  #     - VIRTUAL_HOST=nbviewer.treehouse.gi.ucsc.edu
  #   volumes:
  #     - /data/notebooks:/notebooks
  #   command: python3 -m nbviewer --port=8080 --no-cache --localfiles=/notebooks


  # xena:
  #   image: xena
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.xena
  #   environment:
  #     VIRTUAL_HOST: xena.treehouse.gi.ucsc.edu
  #   volumes:
  #     - /data/xena:/root/xena
