version: '3'

services:
  jupyterhub:
    image: jupyterhub
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - /data:/data
    ports:
      - "80:8000"
    environment:
      - COMPOSE_PROJECT_NAME
      - CONFIGPROXY_AUTH_TOKEN=5879f3780c920dc76456360e23ef2421929b010af2440970f0f3e3ee6cca
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - OAUTH_CALLBACK_URL
      - JUPYTERHUB_API_TOKEN

  nbviewer:
    image: nbviewer
    build:
      context: .
      dockerfile: Dockerfile.nbviewer
    volumes:
      - /data/notebooks:/notebooks
    command: python3 -m nbviewer --port=8080 --no-cache --localfiles=/notebooks
    environment:
      - JUPYTERHUB_API_URL=http://jupyterhub:8080/hub/api
      - JUPYTERHUB_API_TOKEN
      - JUPYTERHUB_BASE_URL=/
      - JUPYTERHUB_SERVICE_PREFIX=/services/nbviewer

# networks:
#   default:

  # xena:
  #   image: xena
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.xena
  #   volumes:
  #     - /data/xena:/root/xena
