FROM jupyter/datascience-notebook

# Install Python 2 & 3 Additional Packages for Notebooks
ADD requirements.txt requirements.txt
RUN conda install --quiet --yes -n python2 --file requirements.txt
RUN conda install --quiet --yes --file requirements.txt

# docker package is not in conda...
RUN pip install -q docker
RUN pip3 install -q docker

# Run as root so we can access everything under /data
USER root
